version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url":"jdbc:mysql://localhost:33061/data_collector?serverTimezone=UTC&useSSL=false",
      "spring.datasource.username":"root",
      "spring.datasource.password":"password",
      "server.port":"8082",
        "spring.profiles.active"="database",
        "spring.mvc.view.prefix"="/WEB_INF/jsp/",
        "spring.mvc.view.suffix"=".jsp"
          }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
